import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Homepage from '../components/Homepage'
import Aboutpage from '../components/Aboutpage'
import Mainproject from '../components/Mainproject'
import Miniproject from '../components/Miniproject'
import Contact from '../components/Contact.js'
import Footer from '../components/Footer'


export default function Home({repos}) {
  return (
    <div>
      <Head>
        <title>Anish Ghimire | Fullstack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-gray-900 '>
        <Homepage/>
        <Aboutpage/>
        <Mainproject/>
        <Miniproject repos={repos} />
        <Contact/>
        <Footer/>
      </main>
      
        
    </div>
  )
}


export async function getStaticProps() {
  // console.log('Generating / Regenerating ProductList')
  const response = await fetch('https://api.github.com/users/ansghimire/repos')
  const data = await response.json()

  return {
      props: {
          repos: data
      },
      revalidate: 30
  }
}